// <auto-generated />
using System;
using AnotadorGymApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnotadorGymApp.Data.Migrations
{
    [DbContext(typeof(DataBase))]
    partial class DataBaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("AnotadorGymApp.Data.BodyParts", b =>
                {
                    b.Property<int>("BodyPartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BodyPart")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BodyPartId");

                    b.ToTable("BodyParts");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.Exercise", b =>
                {
                    b.Property<int>("ExerciseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Iniciar")
                        .HasColumnType("REAL");

                    b.Property<double?>("Mejor")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("Ultimo")
                        .HasColumnType("REAL");

                    b.Property<int>("bodyPartId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("primaryMuscleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ExerciseId");

                    b.HasIndex("bodyPartId");

                    b.HasIndex("primaryMuscleId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.ExerciseLog", b =>
                {
                    b.Property<int>("ExerciseLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkoutDayId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ExerciseLogId");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutDayId");

                    b.ToTable("ExercisesLogs");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.Muscle", b =>
                {
                    b.Property<int>("MuscleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MuscleId");

                    b.ToTable("Muscles");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.RutinaDia", b =>
                {
                    b.Property<int>("DiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiaIdUI")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreRutinaDia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SemanaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DiaId");

                    b.HasIndex("SemanaId");

                    b.ToTable("RutinaDias");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.RutinaEjercicio", b =>
                {
                    b.Property<int>("EjercicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("DiaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EjercicioId");

                    b.HasIndex("DiaId");

                    b.HasIndex("ExerciseId");

                    b.ToTable("RutinaEjercicios");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.RutinaSemana", b =>
                {
                    b.Property<int>("SemanaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreSemana")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RutinaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SemanaIdUI")
                        .HasColumnType("INTEGER");

                    b.HasKey("SemanaId");

                    b.HasIndex("RutinaId");

                    b.ToTable("RutinaSemanas");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.RutinaSeries", b =>
                {
                    b.Property<int>("SerieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descanso")
                        .HasColumnType("TEXT");

                    b.Property<int>("EjercicioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstadoSerie")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Porcentaje1RM")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Repeticiones")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("SerieId");

                    b.HasIndex("EjercicioId");

                    b.ToTable("RutinaSeries");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.Rutinas", b =>
                {
                    b.Property<int>("RutinaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dificultad")
                        .HasColumnType("TEXT");

                    b.Property<string>("FrecuenciaPorGrupo")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageSource")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TiempoPorSesion")
                        .HasColumnType("TEXT");

                    b.HasKey("RutinaId");

                    b.ToTable("Rutinas");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.SetLog", b =>
                {
                    b.Property<int>("SetLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseLogId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Kilos")
                        .HasColumnType("REAL");

                    b.Property<int>("Reps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("SetLogId");

                    b.HasIndex("ExerciseLogId");

                    b.ToTable("SetLogs");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.WorkoutDay", b =>
                {
                    b.Property<int>("DayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("Volumen")
                        .HasColumnType("REAL");

                    b.HasKey("DayId");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("WorkoutDay");
                });

            modelBuilder.Entity("ExerciseMuscle", b =>
                {
                    b.Property<int>("ExercisesAsSecundaryExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("secondaryMusclesMuscleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ExercisesAsSecundaryExerciseId", "secondaryMusclesMuscleId");

                    b.HasIndex("secondaryMusclesMuscleId");

                    b.ToTable("ExerciseSecondaryMuscles", (string)null);
                });

            modelBuilder.Entity("AnotadorGymApp.Data.Exercise", b =>
                {
                    b.HasOne("AnotadorGymApp.Data.BodyParts", "bodyPart")
                        .WithMany("ExercisesList")
                        .HasForeignKey("bodyPartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnotadorGymApp.Data.Muscle", "primaryMuscle")
                        .WithMany("ExercisesAsMain")
                        .HasForeignKey("primaryMuscleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("bodyPart");

                    b.Navigation("primaryMuscle");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.ExerciseLog", b =>
                {
                    b.HasOne("AnotadorGymApp.Data.Exercise", "Exercise")
                        .WithMany("ExerciseLogs")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnotadorGymApp.Data.WorkoutDay", "WorkoutDay")
                        .WithMany("ExerciseLogs")
                        .HasForeignKey("WorkoutDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutDay");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.RutinaDia", b =>
                {
                    b.HasOne("AnotadorGymApp.Data.RutinaSemana", "Semana")
                        .WithMany("Dias")
                        .HasForeignKey("SemanaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Semana");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.RutinaEjercicio", b =>
                {
                    b.HasOne("AnotadorGymApp.Data.RutinaDia", "Dia")
                        .WithMany("Ejercicios")
                        .HasForeignKey("DiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnotadorGymApp.Data.Exercise", "Exercise")
                        .WithMany("RutinasEjercicios")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dia");

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.RutinaSemana", b =>
                {
                    b.HasOne("AnotadorGymApp.Data.Rutinas", "Rutina")
                        .WithMany("Semanas")
                        .HasForeignKey("RutinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rutina");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.RutinaSeries", b =>
                {
                    b.HasOne("AnotadorGymApp.Data.RutinaEjercicio", "Ejercicio")
                        .WithMany("Series")
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ejercicio");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.SetLog", b =>
                {
                    b.HasOne("AnotadorGymApp.Data.ExerciseLog", "ExerciseLog")
                        .WithMany("SetsLog")
                        .HasForeignKey("ExerciseLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExerciseLog");
                });

            modelBuilder.Entity("ExerciseMuscle", b =>
                {
                    b.HasOne("AnotadorGymApp.Data.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExercisesAsSecundaryExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnotadorGymApp.Data.Muscle", null)
                        .WithMany()
                        .HasForeignKey("secondaryMusclesMuscleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnotadorGymApp.Data.BodyParts", b =>
                {
                    b.Navigation("ExercisesList");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.Exercise", b =>
                {
                    b.Navigation("ExerciseLogs");

                    b.Navigation("RutinasEjercicios");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.ExerciseLog", b =>
                {
                    b.Navigation("SetsLog");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.Muscle", b =>
                {
                    b.Navigation("ExercisesAsMain");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.RutinaDia", b =>
                {
                    b.Navigation("Ejercicios");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.RutinaEjercicio", b =>
                {
                    b.Navigation("Series");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.RutinaSemana", b =>
                {
                    b.Navigation("Dias");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.Rutinas", b =>
                {
                    b.Navigation("Semanas");
                });

            modelBuilder.Entity("AnotadorGymApp.Data.WorkoutDay", b =>
                {
                    b.Navigation("ExerciseLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
